# Generated by Django 2.2.7 on 2019-11-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_b', models.CharField(max_length=255)),
                ('pub_date_b', models.DateField()),
                ('body_b', models.TextField()),
                ('image_b', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
